### ISSUE TITLE
Image asset does not expose "source" to Nuxt.

### ISSUE THREAD

**Issue by eggnstone** [storyblok/storyblok-nuxt#253] opened 2022-12-18 09:28 UTC
[storyblokurl]: https://www.storyblok.com?utm_source=github.com&utm_medium=issue-template

Using Storyblok v2 and Nuxt3 and TypeScript.

---

## Expected Behavior

Accessing an image asset I expect all fields to be exposed.

## Current Behavior

Accessing an image asset all fields are be exposed but "source":
```
{"id":5844455,
"alt":"the alt text",
"name":"",
"focus":"392x214:393x215",
"title":"the title text",
"filename":"https://a.storyblok.com/xyz.jpg",
"copyright":"the copyright text",
"fieldtype":"asset",
"is_external_url":false}
```

## Steps to Reproduce

1. Create an asset and set all fields.
2. Try to access the source field.

```
const props = defineProps({blok: Object, relations: [Object]});
const propsBlok = props.blok;
const propsBlokFeaturedImage = propsBlok['FeaturedImage'];
console.log("propsBlokFeaturedImage: " + JSON.stringify(propsBlokFeaturedImage).replaceAll(",",",\n"));
```

**Comment by eggnstone** [comment] 2022-12-18 09:51
By the way `name` is always empty!

**Comment by eggnstone** [comment] 2022-12-18 09:55
> By the way `name` is always empty!

I just discovered that the field `name` contains the text of the field "Add description..." which appear when you insert an asset into a story.
A bit misleading, no?

**Comment by SebbeJohansson** [comment] 2022-12-19 11:38
What were you planning to use the `source` field for? Havnt considered using that for anything yet so curious!

As for the name, where do you see the `"Add description..."` thing? When I go to assets I am not seeing such a thing!

**Comment by eggnstone** [comment] 2022-12-19 17:19
> What were you planning to use the `source` field for? Havnt considered using that for anything yet so curious!

The field is there so I make use of it :)
I use it to fill in the URL when attribution for an image is required.
The `copyright` field I use for the attribution text.
 
> As for the name, where do you see the `"Add description..."` thing? When I go to assets I am not seeing such a thing!


![image](https://user-images.githubusercontent.com/11562425/208483099-c880b9a2-42ac-471a-a409-63c11d263c41.png)

**Comment by SebbeJohansson** [comment] 2022-12-20 09:41
Huh okay... Interesting. Gonna be interesting to see what Storyblok thinks!

**Comment by stijn-ways** [comment] 2023-04-05 11:52
Indeed @eggnstone,

I'm creating a brand new agency website for my company, and want to use the source for the link to the actual source and the copyright for the text (name of the source). But what I've seen is that you can add the source etc to the image directly from the assets page. But as soon as you're assign that image the a field in the editor, it is empty while all other fields are filled out. Really annoying...

Hopefully they will fix this soon

**Comment by alvarosabu** [comment] 2023-05-03 07:25
I will close this due to inactivity and not being able to reproduce it on the current versions. Please feel free to re-open with a reproduction link if necessary. Thanks

**Comment by stijns96** [comment] 2023-05-03 07:33
Hi @alvarosabu ,

Sorry for the late response. I can't create a reproduction link a.t.m. but have you tried to add it as followed:

1. Go to assets and upload it there.
2. Fill in the source and other fields.
3. Go to content and click on the story where you want to add the image. Don't fill in anything (because this should be done already by filling in while adding it to the assets).
4. Check the object again.

You probably have to do this with a fresh image because of caching or whatever other reason.

**Comment by alvarosabu** [comment] 2023-05-03 07:34
Hi @stijns96 I will quickly try it from the asset manager and give you feedback

**Comment by alvarosabu** [comment] 2023-05-03 07:58
@stijn-ways indeed only happens if the assets are created by the asset manager. I will escalate it to product team

**Comment by Dawntraoz** [comment] 2024-03-05 14:32
Closing this issue since this was fixed by the product team long ago 🤗

**Closed by Dawntraoz** 2024-03-05 14:32 UTC
Labels: pending-author, needs-reproduction
