### ISSUE TITLE
console output "You are not in Draft Mode or in the Visual Editor"

### ISSUE THREAD

**Issue by chrisnoden** [storyblok/storyblok-nuxt#215] opened 2022-10-08 07:53 UTC
a `console.warn` with the message "You are not in Draft Mode or in the Visual Editor" has been left in the release. If this might be helpful then it should only appear in certain environments (eg DEV).

Preferably, developers should be given advice on how to detect draft mode or the visual editor.

**Comment by SebbeJohansson** [comment] 2022-10-09 13:51
I can confirm that this is being displayed both with useStoryblok and useAsyncStoryblok.

**Comment by bkuri** [comment] 2022-11-06 00:08
Still present as of `@storyblok/nuxt v4.4.2`.

**Comment by SebbeJohansson** [comment] 2022-11-06 14:52
@Dawntraoz is this in the pipeline to fix?

**Comment by SebbeJohansson** [comment] 2022-11-06 15:19
The issue is located here: https://github.com/storyblok/storyblok-nuxt/blob/main/lib/src/runtime/composables/useAsyncStoryblok.js#L13
The if state looks at the story, which is true as long as URL is set to something (as far as I can tell, it always is).

Seems like this issue is also in the vue package:
https://github.com/storyblok/storyblok-vue/blob/main/lib/index.ts#L57
and it also seems to exist in the js package.
Tested it using the vue base package:
https://vue-5-minutes--3000.local-credentialless.webcontainer.io/
![image](https://user-images.githubusercontent.com/5083273/200178750-84170277-29e7-45c8-8e3f-b135c733ff72.png)
https://stackblitz.com/edit/vue-5-minutes?file=package.json

My suggested fix for this is to explicitly check if we are in preview mode.
Made a pr with my suggested fix here:
https://github.com/storyblok/storyblok-nuxt/pull/227
It is based on my solution for this in my private portfolio project:
https://github.com/SebbeJohansson/sebbejohansson-front/blob/main/pages/blog/%5Bslug%5D.vue#L6

**Comment by Dawntraoz** [comment] 2022-11-24 11:16
@alexjoverm @manuelschroederdev I remember we had a conversation about this topic. Are we going to take it into account for the 5.0 version of the SDKs?

It could help a lot of people if we do it in the SDKs themselves, and they don't have to do it in their projects.

**Comment by SebbeJohansson** [comment] 2022-11-24 14:38
@Dawntraoz This might be a bit off topic, but is there a nightly built or similar I can use of the nuxt modules/sdk?

**Comment by markus-gx** [comment] 2022-11-25 08:48
For those who need a fix for that on production (e.g Lighthouse Test Accessibility etc.); what I am doing is to load the Storyblok-bridge only when inside of the Visual Editor. You can check that with either pinging the editor and loading it afterwards on `onMounted()` or what I recommend to check if a _storyblok[token] parameter gets passed in the query, verify that token and return the draft version + init the bridge. 

```
//check the route query
if (useRoute()?.query?.['_storyblok_tk[token]']) return 'draft'

//launch Storyblok bridge. 
onMounted(() => {
  if (useContentVersion() === 'draft' && state?.story) {
    useStoryblokBridge(state.story.id, (evStory) => {
      state.story = evStory
    })
  }
})
```

How to validate: https://www.storyblok.com/docs/Guides/storyblok-latest-js#how-to-validate-if-the-user-is-viewing-your-site-in-the-storyblo

**Comment by SebbeJohansson** [comment] 2022-11-25 08:52
@markus-gx great example for how to fix it yourself 😁👍

**Comment by Dawntraoz** [comment] 2023-03-01 10:39
This is already implemented on the JS SDK and will soon be updated on Vue/Nuxt SDKs. See the changes at: https://github.com/storyblok/storyblok-js/pull/247.

**Closed** 2023-03-10 08:45 UTC
Labels: improvement
