### ISSUE TITLE
`useAsyncStoryblok` status code checking on response, throws an error on `error.value?.response.status`

### ISSUE THREAD

**Issue by Dru-S** [storyblok/storyblok-nuxt#329] opened 2023-03-13 09:18 UTC
[storyblokurl]: https://www.storyblok.com?utm_source=github.com&utm_medium=issue-template

## Expected Behavior

The `status` property must be checked not only inside the `error.value.response` object, but also directly inside the `error.value` property of the response:
```js
...

const status = error.value?.response?.status || error.value?.status || false;
  if (status && status >= 400 && status < 600) {
    const message = error.value?.message.message || error.value?.message || '';
    throw createError({ statusCode: status, statusMessage: message });

...
```

## Current Behavior

The `status` property is only checked inside the `error.value.response`, throwing a `caught (in promise) TypeError: Cannot read properties of undefined (reading 'status')` error.

```js
...

if (error.value?.response.status >= 400 && error.value?.response.status < 600) {
  throw createError({ statusCode: error.value?.response.status, statusMessage: error.value?.message.message });

...
```

## Steps to Reproduce

1. Simply try to get a 404 request with the `useAsyncStoryblok`

## Additional informations
```
├── @storyblok/js@2.1.0
├─┬ @storyblok/nuxt@5.3.0
│ └─┬ @storyblok/vue@7.1.0
│   └── @storyblok/js@2.1.0 deduped
└── nuxt@3.2.3
```

**Comment by SebbeJohansson** [comment] 2023-03-23 07:10
Hi @Dru-S! This PR will fix this issue. #316

**Comment by Dawntraoz** [comment] 2023-04-19 12:57
We've already merged the fix from @SebbeJohansson 🎉
@Dru-S can you please download the latest SDK version and let us know if everything works as expected?

In case you face any other issue, let us know creating a new one <3

**Comment by Dru-S** [comment] 2023-04-19 15:05
Hi @Dawntraoz, thanks for the update.

I updated to the latest version of the `@storyblok/nuxt` package only, but unfortunately it still didn't work as expected.
I also update Nuxt to the latest version, and this introduces a new bug since it seems that in the `useAsyncData` they added a `createError`, and the check for the status code inside the `useAsyncStoryblok` it's broken, again.

Here's the screenshot of the diff, for the new `createError` of Nuxt's `useAsyncData`:
<img width="1611" alt="SCRNSHT 2023-04-19 alle 16 57 22" src="https://user-images.githubusercontent.com/12699772/233116212-226cf06b-85f4-4622-9d69-1599e5b73b5e.png">

So, as per my suggestion on the issue, integrating the PR [#316](https://github.com/storyblok/storyblok-nuxt/pull/316) of @SebbeJohansson, this snippets will solve the problem, with the addition of having the compatibility with older and latest versions of Nuxt:
```js
const status = error.value?.response?.status || error.value?.status || error.value?.statusCode || false;
if (status >= 400 && status < 600) {
	const message = error.value?.message.message || error.value?.message || error.value?.statusMessage || 'Something went wrong when fetching from storyblok.';
	throw createError({ statusCode: status, statusMessage: message });
}
```

Thanks!

**Comment by SebbeJohansson** [comment] 2023-04-20 08:39
huh interesting! What exact versions did you test this on and do you have some code I can test it with?
Im trying to replicate it on my own in the meantime.

**Comment by SebbeJohansson** [comment] 2023-04-20 09:09
I can replicate it!
Regarding your suggestion, there are a few things that we might be confused about!
1. `error.value` contains the error object from storyblok, and not a nuxtError. So it does not contain a value called `statusCode`.
Example:
![image](https://user-images.githubusercontent.com/5083273/233312971-dd20cba6-0f71-4ec0-84aa-4246e82004e9.png)
![image](https://user-images.githubusercontent.com/5083273/233314527-89894ff0-190a-403f-895b-4496fb12d3a6.png)
2. Same with `statusMessage`.
![image](https://user-images.githubusercontent.com/5083273/233314742-2dc61db5-4563-47ef-be8b-41d6f4fdee64.png)
3. Since `storyblokApiInstance.get` returns an `ISbError`-object, then we don't have a string inside of `error.value?.message` but rather, it is an `Error` type.

Number 3 might be something that should be changed in the js-client, but the others we can probably handle in this!

My suggestion would be something like:
```ts
  const { data, error } = await useAsyncData<ISbResult, ISbError>(
    `${uniqueKey}-asyncdata`,
    () => storyblokApiInstance.get(`cdn/stories/${url}`, apiOptions),
  );
  const status = error.value?.response?.status || error.value?.status || 500;
  if (status >= 400 && status < 600) {
    const message = error.value?.message?.message || error.value?.message?.name || `${error.value?.message}` || 'Something went wrong when fetching from storyblok.';
    throw createError({ statusCode: status, statusMessage: message });
  }
```
What do you think? I added a fallback to 500 since that's just a general server error that can correspond to "Something went wrong when fetching from storyblok." since we don't know what happened.

@Dawntraoz Can you open this again?

**Comment by Dawntraoz** [comment] 2023-04-20 11:54
@SebbeJohansson reopened, are you planning to work on it, or shall I? Let me know if you need any help.

PS: It will be also nice to document the error handling in the README.md, if you can add it to your PR that would be amazing!

**Comment by SebbeJohansson** [comment] 2023-04-20 12:01
@Dawntraoz Im trying to look at it, but I think this might be too much for me 😅

**Comment by SebbeJohansson** [comment] 2023-04-20 12:08
@Dru-S we have the same versions so that's good! I can reproduce the same issue using just purely the js-client without the nuxt3 module so I think `useAsyncData` is casting the error automatically to a nuxt3 error.
Example here (where the path I'm fetching from obviously doesn't exist so it returns 404):
![image](https://user-images.githubusercontent.com/5083273/233360797-b8f5ca51-2d30-41f3-9118-3dffb601a872.png)
![image](https://user-images.githubusercontent.com/5083273/233360838-a6004f82-6744-42b7-8e0d-7606287d5a20.png)

The casting seems to be completely useless since `useAsyncData` seems to have recently been changed so that it is messing with the error return (or I was completely lost when I made the changes to cast to the `ISbError`-interface.
You can see here that it is supposed to work: <https://nuxt.com/docs/api/composables/use-async-data#:~:text=type%20AsyncData%3CDataT,ErrorT%20%7C%20null%3E>

Maybe it will have to be fine with just returning statusCode and the message?

**Comment by Dawntraoz** [comment] 2023-04-20 12:10
Then, I will ask the Nuxt 3 team for their input on our composable's error handling. I will keep you posted with the PR.

**Comment by Dawntraoz** [comment] 2023-04-21 16:00
I got an answer from Daniel, he suggested me to use $fetch directly instead of asyncData. Also, that we wouldn't directly throw an error but return an error ref which gets filled up if there is an error.

So I will work on a PR with the changes and send it to you to test it locally before merging 🫂

Let's improve the composable to be as good as we want/need 💪

**Comment by SebbeJohansson** [comment] 2023-04-24 21:09
Hi! Sorry for the late response, but been on a trip and then gotten ill sadly. Hopefully I'll be back in the next day or two.

Using pure `$fetch` is interesting. Maybe there is a case to be made for something "easier" to be available from Nuxt, but that's a discussion for a different place. 
Not sure I'm following on "don't throw an error", but I guess it would make sense to pass the info along. I know this was something we were unsure off, and that we discussed. Maybe we should have just talked to Daniel right away 😄

Sounds good. I'll try to test as soon as something is available. 🥳

**Comment by SebbeJohansson** [comment] 2023-05-10 12:09
@Maxino22 Until Storyblok has decided on how to officially do it, I think the best idea is to try-catch it.

```
const {
    slug
} = useRoute().params
const resolveRelations = ['all-services.services']

const story = null;
try {
    story = await useAsyncStoryblok(
        Array.isArray(slug) && slug.length > 0 ? slug.join('/') : 'home', {
            version: 'published',
            resolve_relations: resolveRelations
        }, {
            resolveRelations,
        })
} catch (e) {
  // do something when its a 404.
}
```

**Comment by sumerokr** [comment] 2023-06-05 21:21
Hey, @SebbeJohansson but `useAsyncStoryblok` doesn't throw an error that can be catched.
As of now (v 5.4.9) code looks like this
```
const { data, error } = await useAsyncData(
  `${uniqueKey}-asyncdata`,
  () => storyblokApiInstance.get(`cdn/stories/${url}`, apiOptions)
);

```
and the `error` that we get here is an instance of `H3Error`. It doesn't have `response` property that is checked below
```
if (error.value?.response && error.value?.response.status >= 400 && error.value?.response.status < 600) {
  throw createError({ statusCode: error.value?.response.status, statusMessage: error.value?.message?.message || "Something went wrong when fetching from storyblok." });
}
```
Therefore nothing will be thrown. `useAsyncStoryblok` quietly returns `undefined` as a story.

**Comment by sumerokr** [comment] 2023-06-05 21:44
Moreover, it looks that `response` property doesn't exist even on what `storyblokApiInstance.get` returns for 404 pages. `response` value is just a string that is extracted from `["This record could not be found"]` API response array, see https://github.com/storyblok/storyblok-js-client/blob/main/src/sbFetch.ts#L165

**Comment by Maxino22** [comment] 2023-06-06 06:49
> Been Following up on this I may have a similar instance my current setup is as follow in my pages I have [...slug].vue
> 
> ```
> const { slug } = useRoute().params
> 
> const resolveRelations = ['all-services.services']
> 
> const story = await useAsyncStoryblok(
> 	Array.isArray(slug) && slug.length > 0 ? slug.join('/') : 'home',
> 	{ version: 'published', resolve_relations: resolveRelations },
> 	{
> 		resolveRelations,
> 	}
> )
> ```
> 
> I want to catch 404 urls how will i do that with the useAsynStoryblok

Hry @sumerokr  for a case of using  useAsyncStoryblok the solution to create a 404 error would it be to try catch the undefined returned or i do not quite understand??

**Comment by sumerokr** [comment] 2023-06-06 07:35
@Maxino22 based on my experience that I have described above, 404 error will not be thrown. Therefore it cannot be catched.
As a workaround we could
- check if resolved story is `undefined` // feels too dirty and you can't be sure, that it's really a 404 error. Could be whatever else.
- use `storyblokApiInstance.get` directly, it will throw an error that can be catched
- write your own composable similar to `node_modules/@storyblok/nuxt/dist/runtime/composables/useAsyncStoryblok.mjs` with fixed error handling
- fix, submit a PR and wait SB team to merge it

**Comment by SebbeJohansson** [comment] 2023-06-07 11:50
@Dawntraoz any updates on this?

**Closed** 2023-07-25 09:03 UTC
Labels: bug
