### ISSUE TITLE
storyblok-v2-latest.js is included in non preview page (no bridge should load) in a built page with prerendered content using useAsyncStoryblok.

### ISSUE THREAD

**Issue by SebbeJohansson** [storyblok/storyblok-nuxt#288] opened 2023-01-25 19:37 UTC
[storyblokurl]: https://www.storyblok.com?utm_source=github.com&utm_medium=issue-template

If a page is pre-rendered and should not have the bridge (not in preview mode) storyblok-v2-latest.js is still loaded on the page
---

## Expected Behavior

I expect that storyblok-v2-latest.js should not be included on a pre-rendered page that does not have the bridge current running.

## Current Behavior

Right now storyblok-v2-latest.js is included.
![image](https://user-images.githubusercontent.com/5083273/214669934-f8673b69-1bd8-433b-90f5-7d1e192c152e.png)

## Steps to Reproduce

1. Make a nuxt3 project.
2. Use `useAsyncStoryblok` to fetch the storyblok data.
3. Prerender the pages.
4. Load a pre-rendered page.
5. Watch how `storyblok-v2-latest.js` is loaded.

It could be that I am misunderstanding something when it comes to how `storyblok-v2-latest.js` and the bridge works, but I don't see a reason for it to load in this situation.

**Comment by reinoldus** [comment] 2023-02-02 13:54
Hi,
I am facing the same issue the problem lays in the storyblok-js module.

Here is my pull request: https://github.com/storyblok/storyblok-js/pull/232

I tested my solution and it worked. The issue is that it's not so easy to fix this by forking because every module kind of incorporates other modules and then they are build somehow.

I don't know how all of this is built, but let's hope they respond and adress the issue somehow.

**Comment by SebbeJohansson** [comment] 2023-02-02 14:51
@reinoldus im curious, is there a reason why you are looking at `_storyblok_tk` instead of like `_storyblok`?

**Comment by reinoldus** [comment] 2023-02-02 16:54
@SebbeJohansson I copied that value from another issue along time ago that also tried to get rid of bridge.

_storyblok probably also works, but _storyblok_tk is also set as a get-query var.

**Comment by SebbeJohansson** [comment] 2023-02-03 07:47
@reinoldus i guess that makes sense!

**Comment by oezkancodes** [comment] 2023-02-20 15:06
I would love it if by default the script for the Storyblok Bridge would only load when the user is explicitly in preview mode.

This also conflicts with GDPR laws for anyone here in Europe. Third party scripts should only be loaded after consent.

**Comment by reinoldus** [comment] 2023-02-20 17:23
@oezkancodes great point, please leave a comment here as well: https://github.com/storyblok/storyblok-js/issues/214

So they see that it's not just 2 people annoyed by this

**Comment by Dawntraoz** [comment] 2023-02-28 10:07
Happy to share that this is already solved in the JS SDK https://github.com/storyblok/storyblok-js/pull/247. We will upgrade Nuxt 3 soon when fixing another issue, so we can benefit from it 🎉

I will close this one when it's merged!

**Comment by reinoldus** [comment] 2023-03-01 07:15
@Dawntraoz thank you for your effort! Can you also let me know once the nuxt2 version is upgraded?

**Comment by SebbeJohansson** [comment] 2023-03-01 08:04
@reinoldus I feel like nuxt-2 module needs some love. Looks like it hasnt gotten any for a few months. If I have the time I might look at some stuff there and see if I can upgrade at the same time.

**Comment by Dawntraoz** [comment] 2023-03-10 08:42
If you update & install the packages again @reinoldus @SebbeJohansson @oezkancodes and open the local environment or prod outside Storyblok, now the bridge is not loaded anymore 🎉

We will work on Vue 2/Nuxt 2 these days 👏

**Closed by Dawntraoz** 2023-03-10 08:42 UTC
Labels: enhancement

**Comment by reinoldus** [comment] 2023-03-24 08:33
@Dawntraoz any update on the nuxt2 module?

**Comment by Dawntraoz** [comment] 2023-03-30 13:24
Hi @reinoldus indeed, we will merge today https://github.com/storyblok/storyblok-nuxt-2/pull/123!

Sorry for the late reply, we needed to first upgrade the vue-2 module too, and took us forever, but we are there finally 😍

If you can try it after upgrading, it will be amazing! Any things you face while upgrade or questions you have, let's discuss them there in the issues over nuxt-2 module
