### ISSUE TITLE
Nuxt 3 | Cannot read properties of null (reading 'data') when reload a subpage

### ISSUE THREAD

**Issue by waysagency** [storyblok/storyblok-nuxt#211] opened 2022-09-23 08:51 UTC
Hi all,

I have 2 simple pages. A index.vue and an about-us.vue. Both are really simple. They look like the following:

```vue
<script setup>
const story = await useAsyncStoryblok("home", { version: "draft" });
</script>

<template>
  <div>
    <StoryblokComponent v-if="story" :blok="story.content" />
    <nuxt-link to="/about-us" class="btn btn--primary">About us</nuxt-link>
  </div>
</template>
```

I use _npm run generate_ to create a static version of my site. This works perfectly and everything is working great when navigating with the links, but... When I'm on the about-us page and hit reload, I will get the following error:

![image](https://user-images.githubusercontent.com/76130749/191924164-4163e9c0-cb92-493f-9f1a-0be15865d986.png)

When I go to line 101 (in my editor 121 when formatted) of useAsyncStoryblok.js, I see the following code:

![image](https://user-images.githubusercontent.com/76130749/191924549-72d5892f-f8d6-48d1-a615-e01ed9c3bb1b.png)

The problem here is that _a.vale.data.story_ doesn't exist yet.

I tried to use the useStoryblok and the useAsyncStoryblok, but both with the same error.

Could someone tell me if this is just a bug that should be fixed, or that I'm doing something wrong?

Here is my **package.json**
```json
"devDependencies": {
  "@nuxt/image-edge": "^1.0.0-27719579.87dcdf2",
  "@nuxtjs/tailwindcss": "^5.3.3",
  "@tailwindcss/forms": "^0.5.3",
  "nuxt": "3.0.0-rc.11",
  "sass": "^1.55.0",
  "sass-loader": "^13.0.2"
},
"dependencies": {
  "@storyblok/nuxt": "^4.4.1"
}
```

Thanks in advance!

**Comment by Dawntraoz** [comment] 2022-11-03 10:35
Hi @waysagency 👋

Let's see if we can find the issue here, can you answer these 2 questions to clarify some things, please?

- When you generate your pages with `npm run generate` you see the /about page being generated, isn't it?
- Are you running the preview of the static site with the `preview` script on the package.json? (After talking with the Nuxt core team they told me that we need to preview the static site with this command instead: `npx serve .output/public`)

If both of them are true, try the command I suggest, and let me know if it works.

PS: A recommendation, in hosting providers like Netlify they will ask for the route of the page with a slash '/' at the end, it's better to add in the `NuxtLink` `to` property **'/about/'**, so the generated URL works on production.

**Comment by patrykkurzeja91** [comment] 2022-11-04 09:20
hey @waysagency,
I had the same issue and similar situation - one index.vue and about.vue, and I got the same error but in development mode.
I was struggling to get this done so I started with some workarounds but in the end I found that it is caused by `axios@1.1.3` which was released 20 days ago. I don't see it in Your `package.json` file but IMHO it should be there (maybe You installed it globally?). Just make sure You install `axios@0.27.2` as this is the version used by `storyblok-js`.

My current package.json looks like this:
```
"devDependencies": {
    "nuxt": "3.0.0-rc.12"
  },
  "dependencies": {
    "@nuxtjs/i18n": "8.0.0-beta.3",
    "@storyblok/nuxt": "^4.4.2",
    "axios": "0.27.2",
    "sass": "^1.55.0",
    "sass-loader": "^13.1.0"
  }
```

**Comment by lowbits** [comment] 2022-11-08 16:01
I think by downgrading to axios: 0.27.2 the error is not occurring but not resolved.

If you take a look into the readme, useAsyncStoryblok is a shorthand for

```
<script setup>
  const story = ref(null);
  const storyblokApi = useStoryblokApi();
  const { data } = await useAsyncData(
    'vue',
    async () => await storyblokApi.get(`cdn/stories/vue`, {
    version: "draft"
  })
  );
  story.value = data.value.data.story;

  onMounted(() => {
    useStoryblokBridge(story.value.id, (evStory) => (story.value = evStory));
  });
</script>
```

I think the following line is causing the error:
` story.value = data.value.data.story;`

And the following should do the trick.
` story.value = data.value?.data.story;`

**Comment by pascalwengerter** [comment] 2022-11-17 15:29
Been bitten by this today as well, would be great to have it resolved sometime soon (perhaps it is when support for the official Nuxt3 release gets published?)

**Comment by pascalwengerter** [comment] 2022-11-18 11:07
> 

I'm a bit flabbergasted because I've tried using your workaround via `yarn link` on a cloned `storyblok-nuxt` repo (modified with the `data.value?.data.story` in the right place) next to my local demo - that didn't work due to some Vite server-path permissions and mimetype issues, possibly worth another ticket. 
Next step was just pasting your snippet into my component and finding that the data was indeed empty, so I literally copied the JSON-preview URL the storyblok UI gives you next to what my request was doing and _it turns out my access token had changed_?! 🤷🏽  No clue why it was still serving the `home` page fine though

**Comment by sigtm** [comment] 2022-12-09 11:01
I'm seeing this issue too. Hopefully this isn't a read herring, but I noticed that when it happens:

1. In my network tab, the initial request returns a 301, as it has `&cv=undefined`
2. I _think_ `await useAsyncData` resolves when that happens? But there's no response data, so we get an error.
3. Then the redirected request happens, with a `cv` value.
4. That request resolves fine, with the story data, but it's too late.

When I simply `await storyblokApiInstance.get(...)` instead, everything is fine. Not sure how not using `useAsyncData` affects SSR, but we are rendering our site statically so I don't think it's an issue for us 🤔

Again, might be a red herring but maybe someone smarter than me can make sense of it.

<img width="906" alt="image" src="https://user-images.githubusercontent.com/18282258/206687185-8ba2e546-7e0d-47c0-a976-158964009556.png">

**Comment by sigtm** [comment] 2022-12-09 12:33
FWIW I gave up on using `useAsyncData`/`useAsyncStoryblok` for this. In my case, when `await useAsyncData` resolves, `pending` is true. So you definitely can't just set `story.value = data.value.data.story` immediatley.

I tried wrapping `useAsyncData`'s return object in a promise that watches `pending` an resolves when it becomes false, but it never did. No idea why 🤷 But for a static site, awaiting the API call directly in `<script setup>` seems to work ok.

**Comment by mariuscdejong** [comment] 2023-01-03 10:46
Any updates on this issue? Not using useAsyncData/useAsyncStoryblok is not really an option since the statically generated site will still make API-calls. The point of SSG is not having any API-calls during client side navigation. I think this is a really important issue that needs to be resolved.

**Comment by waysagency** [comment] 2023-01-10 12:05
I found out that I have this problem as soon as I use the [...slug].vue dynamic page. Another thing that is happening with this setup, is that it will always make an API call on route change or page load.

Any updates on this? In my opinion this is quite important to update really soon.

**Comment by changefox** [comment] 2023-01-24 01:06
Also getting this error randomly. I can't reproduce it consistently; just sometimes when I load a page it will fail to load and display this error in the console.

In the meantime; is there a way to catch the error and at least present something to the user? :(

I'm using us servers

**Comment by k16e-me** [comment] 2023-01-24 13:33
I couldn't type it, I intended to make a video, but reading through captures what I've had to deal with for the past 2 weeks with a new project in Nuxt 3 + Storyblok. As soon as I turn off Storyblok, I'm in heaven; turn my beautiful CMS back on and I'm roasting. 

In my case, console.log(story.value) gives me the right content from Storyblok. So, I cannot say what is exactly happening except my hazarded guess would go something like "Nuxt doesn't seem to honor its own API manners as it all too eagerly tries to load StoryblokComponent before its own promise has resolved." Crude?

So, if I comment out `<!-- <StoryblokComponent v-if="story" :blok="story.content"/> -->` and load the page and then bring it back just moments later, then it's fine because `story`'s now available. When the actual code looks 

```
<template>
    <div v-if="pending">
        Loading spinner here...
    </div>
    <div v-else>
        <!-- <StoryblokComponent v-if="story" :blok="story.content"/> -->
    </div>
</template>
```

Because I'm using, and I've tried almost all of them, just now guessing and struggling, not knowing where the problem's coming from `useLazyAsyncData`, `useAsyncData`, `useLazyFetch`, etc

My understanding from the doc is that `pending` would be displayed and stay on until Storyblok call is resolved or rejected and then I would have either `story` or get a 404. Instead, my app keeps breaking on:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/52034326/214307532-579c330d-13c7-42b8-8959-5b1d3e72af72.png">

Meantime, here's the rest of my code inside of `pages/[...slug.vue]`

```
const config = useRuntimeConfig()
const url = () => {
    const
        { path } = useRoute(),
        pathArray = String(path).split('/')
    if (path === '/') return 'home'
    else if (pathArray.length > 2) return path
    return `pages${path}`
}
const path = url()

const { pending, data: story } = useLazyAsyncData(async () => {
    try {
        const response = await useStoryblok(path, {
            version: config.storyblokVersion,
            resolve_links: 'story'
        })
        if(!response) {
            throw createError({
                statusCode: 404,
                statusMessage: 'Page Not Found',
                fatal: true
            })
        }
        return response
    } catch (e) { console.log('Storyblok error: ', e) }
})

watch(story, (newStory) => { story.value = newStory })

// const story = await useStoryblok(url(), {
//     version: config.storyblokVersion,
//     resolve_links: 'url'
// })
console.log(story)
```

This is very serious, has stalled this project. It's my first try on Nuxt 3 with Storyblok and I wonder if it's a Nuxt 3 or Storyblok issue. I might just copy the whole thing verbatim and paste as issue in Nuxt 3.

**Comment by sigtm** [comment] 2023-01-24 13:42
In our case, switching from SSG to SSR seemed to sidestep this issue. Which was not really the plan, but at least we got our site up in the end.

**Comment by k16e-me** [comment] 2023-01-24 14:05
> In our case, switching from SSG to SSR seemed to sidestep this issue. Which was not really the plan, but at least we got our site up in the end.

How'd you do that (and does it now work fine on local dev)? Or do you mean from SSG to SSR, confused 😕

**Comment by oezkancodes** [comment] 2023-02-18 17:31
Hey guys, I am sure I have solved the problem.

## Issue

The issue is the `key` in `useAsyncData`. For example, take the following example where the key of `useAsyncData` is set through the path of the router. The result will be that there can be **two key for one page**, once with "/" at the end and once because `route.path` is dynamic.

```
const route = useRoute();
const { data: story, error } = await useAsyncData(route.path, async () => {
  const res: Story = await storyblokApi.get('cdn/stories' + route.path);
  return res.data.story;
});
```

If you type "/foo/bar" into your browser you will land on "/foo/bar", but when navigating client-side, the vue-router will set the path (sometimes) to "/foo/bar/" (see last slash) automatically. Therefore, the keys are not matched and the error happens. This only happens after generating the pages statically with `npm run generate`.

## Solution

You have to remove the last "/" in `route.path` so that the key is always the same. For this, you can create a very simple if query:

```
const route = useRoute();
let path = route.path;

if (path.length > 2 && path.charAt(path.length - 1) === '/') {
  path = path.slice(0, -1);
}
const { data: story, error } = await useAsyncData(path, async () => {
  const res: Story = await storyblokApi.get('cdn/stories' + path);
  return res.data.story;
});
```

Now the error should be gone, and the error should be gone!

## Further

Without knowing for sure, I think that the key is set incorrectly with `useAsyncStoryblok` and that's how the error occurs.

If you have still problems, sometime (for me) `npm run generate` has some troubles, then navigate to the output folder with `cd dist` and start your own server with `npx serve`.

**Comment by Dawntraoz** [comment] 2023-02-28 10:01
Hi @oezkancodes, thanks a lot for your insights on this matter. This was really helpful!! 💜

Apart from this, we are improving the composable, handling the errors properly, and trying to give the best result to the devs. We improved a bit on this version https://github.com/storyblok/storyblok-nuxt/releases/tag/v5.1.0, but we are still making some changes to make it better and handle each case appropriately. Feel free to check and give your opinion on the changes; we would love your feedback!

Let's close this issue then, and as you said, the Nuxt team suggests using `npx serve .output/public` for static sites, as you mentioned 🎉

**Closed by Dawntraoz** 2023-02-28 10:01 UTC
Labels: bug, investigation
