### ISSUE TITLE
Nuxt rich-text-resolver ERROR

### ISSUE THREAD

**Issue by Auraya86** [storyblok/storyblok-nuxt#209] opened 2022-09-22 12:00 UTC
Dear support,

I need some help, because I cant start my application anymore. I got this simpel message here, if I run npm run app:serve
```

Nuxt Fatal Error                                                                   │
   │                                                                                        │
   │   Error: Cannot find module 'storyblok-js-client/dist/rich-text-resolver.es'   
```

This .es-File itself is missing in node_modules. There are only those two files. Is this a generel problem on storyblog-js-client? 

-  node_modules/storyblok-js-client/dist/rich-text-resolver.cjs.js
-  node_modules/storyblok-js-client/dist/rich-text-resolver.standalone.js

general information:
- macos
-  node v14.16.1
- npm  v6.14.12

clearing cache, reinstall node, npm doesnt seem to fix the error

**Comment by Dawntraoz** [comment] 2023-07-18 12:54
I will close this issue for now since it hasn't been active since a long time ago, and we couldn't reproduce it.

If someone faces it again, please create a new Issue using the SDK Bug template, thanks in advance 🤗

**Closed by Dawntraoz** 2023-07-18 12:54 UTC
Labels: bug, needs-reproduction
